### ISSUE TITLE
not apper in edit menu

### ISSUE THREAD

**Issue by dimohamdy** [aotian16/SwiftJsonToObj#1]
this plugin not show in edit menu in XCode 7.2

**Comment by aotian16** [comment]
1. Use command `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`, and you will get a uuid.
2. Use command `open ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/SwiftJsonToObj.xcplugin/Contents/Info.plist`, and see the uuid you get is in the `DVTPlugInCompatibilityUUIDs`. If not, add the uuid to `DVTPlugInCompatibilityUUIDs`
3. restart Xcode

**Comment by dimohamdy** [comment]
it's work now
